version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: les2023
      POSTGRES_DB: les2023
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
