version: "3.7"
services:
  db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: les2023
      POSTGRES_DB: les2023
    ports:
      - "5433:5432"
      
